### PR TITLE
PmtYaml: Parser fixes

### PR DESCRIPTION
**Pull request by frankosterfeld**
* Make sure block-style maps in block-style lists are parsed
    correctly. This is needed to parse our existing GRC files.
```
 - name: foo
   id: bar
```

 * Support unexpected whitespace/newlines between key and scalars
       as well as flow-style maps/lists. E.g.
```
string:
  "foo"
list:
 []
map: {
}
```

### CODE REVIEW

**Review by wirew0rm — APPROVED** [review]
Looks good, thanks for adding this :+1: can be merged once the CI has passed.

**Comment by frankosterfeld** [comment]
> Looks good, thanks for adding this 👍 can be merged once the CI has passed.

@wirew0rm I'd first like @dantti to confirm that it fixes all his issues with parsing our existing GRC test cases.

**Comment by frankosterfeld** [comment]
> Looks good, thanks for adding this 👍 can be merged once the CI has passed.

Please re-review, I've changed it completely again.. @dantti Please test with your GRC parsing changes.

**Review by RalphSteinhagen — APPROVED** [review]
Still ok. If this solves @dantti issue, then I'd merge it as is.

**Pull request merged**
